export const ROUTE_CATALOG = {
  principales: [
    { id: "P1", name: "P1 (La Rosita - Playa)" },
    { id: "P2", name: "P2 (Alberro - Vedado)" },
    { id: "P3", name: "P3 (Alamar - Túnel de La Habana)" },
    { id: "P4", name: "P4 (San Agustín - Terminal de Trenes)" },
    { id: "P5", name: "P5 (San Agustín - Terminal de Trenes)" },
    { id: "P6", name: "P6 (Reparto Eléctrico - Vedado)" },
    { id: "P7", name: "P7 (Alberro - Parque de la Fraternidad)" },
    { id: "P8", name: "P8 (Reparto Eléctrico - Villa Panamericana)" },
    { id: "P9", name: "P9 (CUJAE - La Palma)" },
    { id: "P10", name: "P10 (Víbora - Playa)" },
    { id: "P11", name: "P11 (Alamar - Vedado)" },
    { id: "P12", name: "P12 (Santiago de las Vegas - P. Fraternidad)" },
    { id: "P13", name: "P13 (Santiago de las Vegas - P. Fraternidad)" },
    { id: "P14", name: "P14 (San Agustín - P. Fraternidad)" },
    { id: "P15", name: "P15 (Alamar - Guanabacoa)" },
    { id: "P16", name: "P16 (Santiago de las Vegas - Hosp. Ameijeiras)" }
  ],
  alimentadoras: [
    { id: "A1", name: "A1 (Playa - Vedado)" },
    { id: "A2", name: "A2 (Guanabacoa - Vedado)" },
    { id: "A3", name: "A3 (San Agustín - Playa)" },
    { id: "A5", name: "A5 (Palatino - Vedado)" },
    { id: "A10", name: "A10 (Playa - Vado del Yeso)" },
    { id: "A13", name: "A13 (La Palma - Vedado)" },
    { id: "A14", name: "A14 (San Agustín - Guanabacoa)" },
    { id: "A16", name: "A16 (La Palma - San Agustín)" },
    { id: "A18", name: "A18 (Cotorro - Vedado)" },
    { id: "A20", name: "A20 (Plaza - Terminal de Trenes)" },
    { id: "A27", name: "A27 (Palatino - San Agustín)" },
    { id: "A32", name: "A32 (Guanabacoa - Regla)" },
    { id: "A40", name: "A40 (Guanabacoa - Estación Central)" },
    { id: "A50", name: "A50 (Alamar - Guanabacoa)" },
    { id: "A58", name: "A58 (Casablanca - Guanabacoa)" },
    { id: "A65", name: "A65 (Cotorro - Virgen del Camino)" },
    { id: "A83", name: "A83 (Terminal Santiago - Rpto. Eléctrico)" }
  ],
  ruteros: [
    { id: "RUT-1", name: "Ruta 1 (Secundaria Reparto Electrico Arroyo Naranjo - Calle 5ta y D)" },
    { id: "RUT-2", name: "Ruta 2 (Frente Policlínico Capdevila Boyeros - Interior del Parqueo Estatal)" },
    { id: "RUT-3", name: "Ruta 3 (San Agustín - Parque Las Piedras)" },
    { id: "RUT-4", name: "Ruta 4 (Santiago de las Vegas - 27 y O)" },
    { id: "RUT-5", name: "Ruta 5 (Santiago de las Vegas - Estacion Central FCC)" },
    { id: "RUT-6", name: "Ruta 6 (Santa Fe Guanabacoa - Interior del Parqueo Estatal)" },
    { id: "RUT-7", name: "Ruta 7 (Santa Fe - Estacion Central FCC)" },
    { id: "RUT-8", name: "Ruta 8 (La Contuco. Cotorro - Calle 5ta y D)" },
    { id: "RUT-10", name: "Ruta 10 (Emboque Regla - Flores)" },
    { id: "RUT-11", name: "Ruta 11 (Base Taxis 82 - Hospital Pando Ferrer)" },
    { id: "RUT-12", name: "Ruta 12 (La Contuco - 3ra A y 80)" },
    { id: "RUT-13", name: "Ruta 13 (El Roble - 3ra A y 80)" },
    { id: "RUT-14", name: "Ruta 14 (Punta Brava - Calle K)" },
    { id: "RUT-15", name: "Ruta 15 (Avenida los Cocos y Edificio 18 Plantas - Calle 5ta y D)" },
    { id: "RUT-16", name: "Ruta 16 (Alamar Micro X - 3ra A y 80)" },
    { id: "RUT-17", name: "Ruta 17 (Managua - Parque de La Normal)" },
    { id: "RUT-18", name: "Ruta 18 (Alamar Micro X Habana del Este - Calle K)" },
    { id: "RUT-19", name: "Ruta 19 (San Agustin - Parque Las Piedras)" },
    { id: "RUT-20", name: "Ruta 20 (Base Taxis 82 - Flores)" },
    { id: "RUT-21", name: "Ruta 21 (Managua - Parque Santiago de las Vegas)" },
    { id: "RUT-22", name: "Ruta 22 (Reparto Bahía - Interior del Parqueo Estatal)" },
    { id: "RUT-23", name: "Ruta 23 (Centro Comercial Fontanar - Hospital Pando Ferrer)" },
    { id: "RUT-24", name: "Ruta 24 (Jaimanita - 27 y O)" },
    { id: "RUT-25", name: "Ruta 25 (Ave. Independencia y 19 de Mayo - Zulueta y Arsenal)" },
    { id: "RUT-26", name: "Ruta 26 (Arsenal y Zulueta - Marina y San Lázaro)" }
  ],
  complementarias: [
    { id: "8", name: "8" },
    { id: "14", name: "14 (Lisa - Vedado)" },
    { id: "34", name: "34" },
    { id: "34L", name: "34L" },
    { id: "36", name: "36" },
    { id: "43", name: "43" },
    { id: "45", name: "45" },
    { id: "46", name: "46" },
    { id: "55", name: "55 (Lisa - Vedado)" },
    { id: "69", name: "69" },
    { id: "92", name: "92" },
    { id: "93", name: "93 (Cotorro - P. Fraternidad)" },
    { id: "113", name: "113" },
    { id: "160", name: "160" },
    { id: "174", name: "174 (San Agustín - Vedado)" },
    { id: "177", name: "177" },
    { id: "179", name: "179 (Cotorro - Terminal de Trenes)" },
    { id: "180", name: "180" },
    { id: "191", name: "191 (Alamar - Guanabacoa)" },
    { id: "192", name: "192" },
    { id: "193", name: "193" },
    { id: "201", name: "201 (Alamar - Habana Vieja)" },
    { id: "202", name: "202 (La Palma - Playa)" },
    { id: "222", name: "222 (Lisa - Parque de la Fraternidad)" },
    { id: "400", name: "400" },
    { id: "420", name: "420 (Guanabacoa - Vedado)" },
    { id: "436", name: "436" },
    { id: "440", name: "440" },
    { id: "450", name: "450" },
    { id: "450A", name: "450A" },
    { id: "450CF", name: "450CF" },
    { id: "473", name: "473" },
    { id: "476", name: "476" },
    { id: "486", name: "486" },
    { id: "487", name: "487" },
    { id: "488", name: "488" },
    { id: "490", name: "490" },
    { id: "C1", name: "C1 (Cotorro - Vedado)" },
    { id: "C1CF", name: "C1CF" },
    { id: "C2", name: "C2 (Cotorro - San Miguel)" },
    { id: "C3", name: "C3" },
    { id: "C4", name: "C4" },
    { id: "C5", name: "C5" },
    { id: "C5L", name: "C5L" },
    { id: "C6", name: "C6" },
    { id: "C7", name: "C7" },
    { id: "CB", name: "CB" },
    { id: "CXXN", name: "CXXN" },
    { id: "IP", name: "IP" },
    { id: "R1", name: "R1" },
    { id: "R15", name: "R15" },
    { id: "R23", name: "R23" },
    { id: "R25", name: "R25" },
    { id: "R37", name: "R37" },
    { id: "R54", name: "R54" },
    { id: "R88", name: "R88" },
    { id: "T1", name: "T1 (Habana Bus Tour)" },
    { id: "T2", name: "T2 (Habana Bus Tour)" },
    { id: "T3", name: "T3 (Habana Bus Tour)" }
  ]
};

export const COMMON_ROUTES = [
  ...ROUTE_CATALOG.principales.map(r => r.id),
  ...ROUTE_CATALOG.alimentadoras.map(r => r.id),
  ...ROUTE_CATALOG.ruteros.map(r => r.id),
  ...ROUTE_CATALOG.complementarias.map(r => r.id),
];
